---
title: "Brooklyn Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    theme: yeti
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(p8105.datasets)

rest_inspec

rest_inspec =
  rest_inspec %>% 
  select(action, boro, camis, critical_flag, cuisine_description, dba, score, violation_code, violation_description, zipcode, grade) %>% 
  filter(boro == "BROOKLYN") %>% 
  drop_na(grade)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Food scores by zipcode in Brooklyn

```{r}
rest_inspec %>% 
  janitor::clean_names() %>% 
  plot_ly(x = ~zipcode, y = ~score, color = ~grade, alpha = 0.5, 
    type = "scatter", mode = "markers") %>% 
  layout(xaxis = list(type = 'category', title = 'Zipcode'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Twenty most common cuisine types in Brooklyn

```{r}
rest_inspec %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  top_n(20, cuisine_description) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description,
          type = "bar", colors = "viridis", showlegend = F) %>% 
  layout(xaxis = list(type = 'category', title = 'Cuisine Type'))

```

### Food scores of twenty most common cuisine types in Brookyln

```{r}
top_cuisines =
  rest_inspec %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  top_n(20, cuisine_description) 

rest_inspec %>%
  filter(cuisine_description %in% pull(top_cuisines,cuisine_description)) %>% 
  plot_ly(y = ~score, x = ~cuisine_description, color = ~cuisine_description,
          type = "box", ccolors = "viridis", showlegend = F) %>% 
  layout(xaxis = list(type = 'category', title = 'Cuisine Type'))
```



